### ISSUE TITLE
Password in keyring or kerberos auth

### ISSUE THREAD

**Issue by mriehl** [ImmobilienScout24/afp-cli#18]
It sucks that I have to retype my password all the time. It would be easier and more secure if this could work automagically (kerberos) or at least with password caching (keyring).

:-1: for keyring since this stores the password on disk though.

**Comment by schlomo** [comment]
Maybe https://pypi.python.org/pypi/keyring will help with caching the password. Kerberos is of course much better from a security perspective.

**Comment by mriehl** [comment]
I'd also rather see kerberos support... I could probably put a pull request together for keyring caching though.

I found https://pypi.python.org/pypi/kerberos/1.2.2 but I have no clue about kerberos. I wonder if you have any guidance on approaching this, maybe this was discussed internally already?

**Comment by h1f1x** [comment]
I like to have a credential remembering feature too.
Because I've already stored credentials in the systems keystore, I can  live with with the keyring solution. maybe its worth to take a look at. :)

**Comment by esc** [comment]
We should get to this soon, the danger is that people may come up with custom solutions to store the password on disk 'somewhere' . Also, not sure if the keystore will help on DC hosts.

**Comment by schlomo** [comment]
IMHO keystore is a valid option and puts the responsability on the user.
Kerberos would be better, but I see that as another evolutionary step.

For DC hosts neither keystore (no good backend in shell session available)
nor Kerberos (clients are not joined into AD) are viable options. There I
would look for a solution that trusts the logged in user.

**Comment by esc** [comment]
So this has been implemented in #27

**Comment by heroldus** [comment]
Done, if you ask me! 

Great job @esc!

**Comment by esc** [comment]
@heroldus thanks for the feedback, much appreciated. The reason I haven't close this yet, is because Kerberos is still missing, but perhaps I'll open a new issue for that.

**Comment by h1f1x** [comment]
Thanks. Works fine on MacOSX :)

**Comment by esc** [comment]
@h1f1x thanks for the feedback, much appreciated!
